# Generated by Django 5.2.5 on 2025-08-09 21:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del taller', max_length=100, verbose_name='Nombre del taller')),
                ('descripcion', models.TextField(help_text='Descripción detallada del taller, objetivos y metodología', verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(help_text='Fecha en que inicia el taller', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha en que finaliza el taller', verbose_name='Fecha de fin')),
                ('horario', models.CharField(help_text="Horario del taller, por ejemplo: 'Lunes y Miércoles de 15:00 a 17:00'", max_length=100, verbose_name='Horario')),
                ('lugar', models.CharField(help_text='Lugar donde se realiza el taller', max_length=200, verbose_name='Lugar')),
                ('capacidad', models.PositiveIntegerField(help_text='Número máximo de participantes permitidos', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad máxima')),
                ('facilitador', models.CharField(help_text='Nombre del facilitador o responsable del taller', max_length=200, verbose_name='Facilitador')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20, verbose_name='Estado del taller')),
                ('notas', models.TextField(blank=True, help_text='Información adicional o requisitos especiales', null=True, verbose_name='Notas adicionales')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, help_text='Nombres del participante', max_length=100, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, help_text='Apellidos del participante', max_length=100, null=True, verbose_name='Apellidos')),
                ('dni', models.CharField(blank=True, help_text='Número de DNI', max_length=8, null=True, verbose_name='DNI')),
                ('telefono', models.CharField(blank=True, help_text='Número de contacto', max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Dirección de correo electrónico', max_length=254, null=True, verbose_name='Correo electrónico')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, help_text='Fecha en que se registró la inscripción', verbose_name='Fecha de inscripción')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmación'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='CONFIRMADO', max_length=20, verbose_name='Estado de la inscripción')),
                ('notas', models.TextField(blank=True, help_text='Observaciones o información adicional sobre el participante', null=True, verbose_name='Notas')),
                ('beneficiaria', models.ForeignKey(blank=True, help_text='Seleccione si el participante es una beneficiaria ya registrada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiarias.beneficiaria', verbose_name='Beneficiaria')),
                ('taller', models.ForeignKey(help_text='Taller en el que está inscrito el participante', on_delete=django.db.models.deletion.CASCADE, to='talleres.taller', verbose_name='Taller')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['taller', 'apellidos', 'nombres'],
                'unique_together': {('taller', 'beneficiaria'), ('taller', 'dni')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha en que se realiza la evaluación', verbose_name='Fecha de evaluación')),
                ('titulo', models.CharField(help_text='Título o nombre de la evaluación', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la evaluación o criterios evaluados', verbose_name='Descripción')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=1, help_text='Calificación numérica (si aplica)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Calificación')),
                ('nivel_logro', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('NECESITA_MEJORAR', 'Necesita mejorar'), ('NO_EVALUADO', 'No evaluado')], default='NO_EVALUADO', max_length=20, verbose_name='Nivel de logro')),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios adicionales sobre el desempeño o logros', null=True, verbose_name='Comentarios')),
                ('evaluador', models.CharField(help_text='Persona que realizó la evaluación', max_length=100, verbose_name='Evaluador')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('participante', models.ForeignKey(help_text='Participante que está siendo evaluado', on_delete=django.db.models.deletion.CASCADE, to='talleres.participante', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha', 'participante'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título o nombre del material', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(help_text='Descripción breve del contenido del material', verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('DOCUMENTO', 'Documento'), ('PRESENTACION', 'Presentación'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('IMAGEN', 'Imagen'), ('ENLACE', 'Enlace'), ('OTRO', 'Otro')], default='DOCUMENTO', max_length=20, verbose_name='Tipo de material')),
                ('archivo', models.FileField(blank=True, help_text='Archivo del material (si aplica)', null=True, upload_to='talleres/materiales/', verbose_name='Archivo')),
                ('url', models.URLField(blank=True, help_text='Enlace externo al material (si aplica)', null=True, verbose_name='URL')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('autor', models.CharField(blank=True, help_text='Autor o creador del material', max_length=200, null=True, verbose_name='Autor')),
                ('taller', models.ForeignKey(help_text='Taller al que pertenece el material', on_delete=django.db.models.deletion.CASCADE, to='talleres.taller', verbose_name='Taller')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la sesión del taller', verbose_name='Fecha de la sesión')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('TARDANZA', 'Tardanza'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Ausencia justificada')], default='PRESENTE', max_length=20, verbose_name='Estado de asistencia')),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre la asistencia o comportamiento', null=True, verbose_name='Observaciones')),
                ('registrado_por', models.CharField(help_text='Persona que registró la asistencia', max_length=100, verbose_name='Registrado por')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('participante', models.ForeignKey(help_text='Participante cuya asistencia se registra', on_delete=django.db.models.deletion.CASCADE, to='talleres.participante', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', 'participante'],
                'unique_together': {('participante', 'fecha')},
            },
        ),
    ]
