# Generated by Django 5.2.5 on 2025-11-06 20:08

import django.db.models.deletion
import talleres.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talleres", "0002_add_fecha_nacimiento_to_participante"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        default=talleres.models.generar_codigo_certificado,
                        help_text="Código único que identifica al certificado",
                        max_length=20,
                        unique=True,
                        verbose_name="Código del certificado",
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que se emitió el certificado",
                        verbose_name="Fecha de emisión",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("EMITIDO", "Emitido"), ("REVOCADO", "Revocado")],
                        default="EMITIDO",
                        max_length=10,
                        verbose_name="Estado del certificado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones o notas adicionales sobre el certificado",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        help_text="Participante al que se emite el certificado",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talleres.participante",
                        verbose_name="Participante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "ordering": ["-fecha_emision"],
            },
        ),
    ]
