# Generated by Django 5.2.5 on 2025-08-09 21:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('hora_ingreso', models.TimeField(default=django.utils.timezone.now)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('documento_identidad', models.CharField(blank=True, max_length=20)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte'), ('CARNET_EXTRANJERIA', 'Carnet de Extranjería'), ('OTRO', 'Otro')], default='DNI', max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTERA', 'Soltera'), ('CASADA', 'Casada'), ('CONVIVIENTE', 'Conviviente'), ('DIVORCIADA', 'Divorciada'), ('VIUDA', 'Viuda')], max_length=20)),
                ('nivel_educativo', models.CharField(blank=True, choices=[('SIN_ESTUDIOS', 'Sin estudios'), ('PRIMARIA_INCOMPLETA', 'Primaria incompleta'), ('PRIMARIA_COMPLETA', 'Primaria completa'), ('SECUNDARIA_INCOMPLETA', 'Secundaria incompleta'), ('SECUNDARIA_COMPLETA', 'Secundaria completa'), ('TECNICO_INCOMPLETO', 'Técnico incompleto'), ('TECNICO_COMPLETO', 'Técnico completo'), ('UNIVERSITARIO_INCOMPLETO', 'Universitario incompleto'), ('UNIVERSITARIO_COMPLETO', 'Universitario completo')], max_length=50)),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('situacion_laboral', models.CharField(blank=True, choices=[('EMPLEADA', 'Empleada'), ('DESEMPLEADA', 'Desempleada'), ('TRABAJADORA_INDEPENDIENTE', 'Trabajadora independiente'), ('AMA_DE_CASA', 'Ama de casa'), ('ESTUDIANTE', 'Estudiante'), ('JUBILADA', 'Jubilada'), ('OTRA', 'Otra')], max_length=50)),
                ('motivo_consulta', models.TextField(blank=True)),
                ('tipo_violencia', models.CharField(blank=True, choices=[('FISICA', 'Física'), ('PSICOLOGICA', 'Psicológica'), ('SEXUAL', 'Sexual'), ('ECONOMICA', 'Económica'), ('PATRIMONIAL', 'Patrimonial'), ('OTRAS', 'Otras')], max_length=50)),
                ('descripcion_situacion', models.TextField(blank=True)),
                ('problemas_salud', models.TextField(blank=True)),
                ('medicacion', models.TextField(blank=True)),
                ('tiene_hijos', models.BooleanField(default=False)),
                ('numero_hijos', models.PositiveIntegerField(default=0)),
                ('situacion_vivienda', models.CharField(blank=True, choices=[('PROPIA', 'Propia'), ('ALQUILADA', 'Alquilada'), ('FAMILIAR', 'Familiar'), ('OTRO', 'Otro')], max_length=50)),
                ('seguimiento_requerido', models.BooleanField(default=False)),
                ('notas_seguimiento', models.TextField(blank=True)),
                ('recibido_por', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Beneficiaria',
                'verbose_name_plural': 'Beneficiarias',
            },
        ),
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('parentesco', models.CharField(choices=[('CONYUGE', 'Cónyuge/Pareja'), ('HIJO_A', 'Hijo/a'), ('PADRE_MADRE', 'Padre/Madre'), ('HERMANO_A', 'Hermano/a'), ('OTRO_FAMILIAR', 'Otro familiar'), ('AMIGO_A', 'Amigo/a'), ('PROFESIONAL', 'Profesional'), ('OTRO', 'Otro')], max_length=50)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('documento_identidad', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('beneficiaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanantes', to='beneficiarias.beneficiaria')),
            ],
            options={
                'verbose_name': 'Acompañante',
                'verbose_name_plural': 'Acompañantes',
            },
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('OTRO', 'Otro')], max_length=10)),
                ('escolaridad', models.CharField(blank=True, max_length=50)),
                ('vive_con_beneficiaria', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('beneficiaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='beneficiarias.beneficiaria')),
            ],
            options={
                'verbose_name': 'Hijo',
                'verbose_name_plural': 'Hijos',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo_atencion', models.CharField(choices=[('PSICOLOGICA', 'Atención psicológica'), ('LEGAL', 'Atención legal'), ('SOCIAL', 'Atención social'), ('MEDICA', 'Atención médica'), ('OTRA', 'Otra')], max_length=50)),
                ('profesional', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField()),
                ('acuerdos', models.TextField(blank=True)),
                ('proxima_cita', models.DateField(blank=True, null=True)),
                ('beneficiaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='beneficiarias.beneficiaria')),
            ],
            options={
                'verbose_name': 'Seguimiento de Caso',
                'verbose_name_plural': 'Seguimientos de Casos',
            },
        ),
    ]
