# Generated by Django 5.2.5 on 2025-11-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaria',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaria',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaria',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
